### ISSUE TITLE
when searching the dashes in names is discarded

### ISSUE THREAD

**Issue by Psycheux** [cheetahsweater/lyrics4lyrics#1]
when testing the search using "SR-71 (Rock)" it correctly gets rid of the parenthesis but also the dash which is necesary for the url

the output of the programme is  : https://www.genius.com/sr71-rock-last-man-on-the-moon-lyrics
when it should be : https://www.genius.com/sr-71-rock-last-man-on-the-moon-lyrics

a work around is to replace the dash with a space in the initial search but it would be nyice to have it just work.
![screencap_3_54](https://github.com/cheetahsweater/lyrics4lyrics/assets/118335552/407c623a-36fa-4337-addc-1654bb2f66bc)

**Comment by cheetahsweater** [comment]
Fixed here: https://github.com/cheetahsweater/lyrics4lyrics/commit/41d19ab08f58a2b94cd37710009a899b0f601a95
