### ISSUE TITLE
add album search (please)

### ISSUE THREAD

**Issue by Psycheux** [cheetahsweater/lyrics4lyrics#3]
an album search that you type the artist then album title (or part of it. Ex : "Sycamour, Indugence" instead or "Sycamour, Indulgence: A Saga Of Lights" but if this isnt possible ill take what i can get xD) and it download either in one text doc with separation or (preferable) split the songs into different txt files with the song titles and artist's name in the beginning.

**Comment by cheetahsweater** [comment]
Added: https://github.com/cheetahsweater/lyrics4lyrics/commit/903f825a09b6af4570e74ff206f753b1c7c49dfe
